apiVersion: v1
kind: Secret
metadata:
  name: {{ include "imageflow.fullname" . }}-secret
  labels:
    {{- include "imageflow.labels" . | nindent 4 }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.secret.awsAccessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.awsSecretAccessKey | b64enc }}
